agent:
  label: jenkins-python
  container: python
pipelines:
  pullRequest:
    build:
      steps:
      - sh: python -m pip install flake8 && flake8
      - sh: python -m pip install pytest hypothesis && pytest
      - sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml
    postBuild:
      steps:
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION
    promote:
      steps:
      - dir: ./charts/preview
        steps:
        - sh: make preview
        - sh: jx preview --app $APP_NAME --dir ../..
  release:
    setup:
      steps:
      - groovy: git 'https://REPLACE_ME_GIT_PROVIDER/REPLACE_ME_ORG/REPLACE_ME_APP_NAME.git'
        when: "prow"
      - sh: git checkout master
        comment: ensure we're not on a detached head
        when: "!prow"
      - sh: git config --global credential.helper store
        when: "!prow"
      - sh: jx step git credentials
        when: "!prow"
    setVersion:
      steps:
      - sh: echo \$(jx-release-version) > VERSION
        comment: so we can retrieve the version in later steps
      # TODO set the version in source?
      - sh: jx step tag --version \$(cat VERSION)
    build:
      steps:
      - sh: python -m pip install flake8 && flake8
#      - sh: python -m pip install pytest hypothesis && pytest
      - sh: python --version
      - sh: cat ~/.git-credentials
      - sh: python app.py
  post:
    steps:
    - groovy: always
      when: "!prow"
      steps:
      - groovy: "cleanWs()"
