extends:
  import: classic
  file: pipeline.yaml

agent:
  label: jenkins-gradle-java11
  container: gradle

pipelines:

  pullRequest:
    build:
      steps:
        - sh: gradle clean build
          name: build
        - sh: gradle aT
          name: accceptancetest
        - sh: export VERSION=$PREVIEW_VERSION && skaffold build -f skaffold.yaml
          name: container-build
    postBuild:
      steps:
        - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:$PREVIEW_VERSION
          name: post-build
    promote:
      steps:
        - dir: ./charts/preview
          steps:
            - sh: make preview
              name: make-preview
            - sh: jx preview --app $APP_NAME --dir ../..
              name: jx-preview

  release:
    setVersion:
      steps:
        - sh: echo \$(jx-release-version) > VERSION
          comment: so we can retrieve the version in later steps
        # TODO
        # - sh: mvn versions:set -DnewVersion=\$(cat VERSION)
        - sh: jx step tag --version \$(cat VERSION)
    build:
      steps:
        - sh: gradle clean build
        - sh: gradle aT
        - sh: export VERSION=`cat VERSION` && skaffold build -f skaffold.yaml
          name: container-build
        - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:\$(cat VERSION)
          name: post-build
    promote:
      steps:
        - dir: ./charts/REPLACE_ME_APP_NAME
          steps:
            - sh: jx step changelog --version v\$(cat ../../VERSION)
              name: changelog
            - comment: release the helm chart
              sh: jx step helm release
              name: helm-release
            - comment: promote through all 'Auto' promotion Environments
              sh: jx promote -b --all-auto --timeout 1h --version \$(cat ../../VERSION)
              name: jx-promote
